Testing Policies:
=================

All courses will require that you take tests to verify that you have learned
the material being presented. For this class, your exams will be written, short
answer problems: I will provide a printed test with space for you to write your
answer. You are not allowed to use any other paper for your answers.

Unless specifically told otherwise, all tests are closed-book tests. I do allow
using any reference materials for lab assignments associated with a test, but
there will be a time limit to complete the work. 
    
