..  csv-table::
    :header: Week, Dates,Topic,Lab,Reading
    :widths: 6, 10, 25, 10, 10

    1,5/30-6/4,,,
    ,5/31,Course Introduction,Lab Setup,1.1-1.5
    ,,History Lesson,,Notes
    ,5/1,Orientation Exam,HW1,Syllabus
    ,,A Peek at Assembly,Lab1,Notes
    ,,Von Neumann Machines,,Notes
    ,,Performance,HW2,1.6
    ,,,,
    2,6/5-6/11,,,	
    ,6/6,Number systems,HW3
    ,,Machine Language,,
    ,,Coding Instructions,,
    ,6/8,Decisions,,
    ,,Procedures,,
    ,,Input/Output,,
    ,,,,
    3,6/12-6/18,,,	
    ,6/13,Doing Math,,
    ,6/14,Review for Exam 1,,
    ,,,,
    4,6/19-6/25,,,
    ,6/20, **Exam 1**, **Ex1 Lab**,
    ,,Processor Design	,,
    ,6/22,Hardware Design Languages,,
    ,,Pipelining,,
    ,,,,
    5,6/26-7/2,,,	
    ,6/27,Pentium&ARM
    ,,Assembly Language,,
    ,6/29,Memory Heirarchy,,
    ,,Caches,,
    ,,,,
    6,7/3-7/9,,,
    ,7/4,**Independence Day**,,
    ,7/6,Virtualization,,
    ,,Group Project 1 Demos,,
    ,,Review for Exam 2,,
    ,,,,
    7,7/10-7/16,,,
    ,7/11,**Exam 2**, **EX2 Lab**,
    ,,Embedded Systems,,
    ,7/13,Timers,,
    ,,,,
    8,7/17-7/23,,,	
    ,7/18,Pulse Width Modulation,,
    ,7/19,Motor Control,,
    ,,,,
    9,7/24-7/30,,, 	
    ,7/25,Interrupts,,
    ,7/27,Multitasking,,
    ,,,,
    10,7/31-8/1,,,
    ,8/1,**Group Project 2 Demos**,,	
 	 

