Office Hours
============

..  csv-table::
    :header:    "Day", "Time", "Room"
    :widths:    20,30,30
    
    TTh, 3:00pm-5:00pm, HLC1-2412 or open lab
    Sat, 10:00am-12:00pm RGC3-3251 (by appointment only)

On Saturdays, I hole ROboLab sessions where we work on course hardware, and
robot projects. I also offer help with personal system setup issues. If needed
I can be available up to 2:00pm, when the campus closes. If no one shows up
before noon, I may leave then, unless you have made an appointment.
