
    * Computers are constructed out of basic components interconnected
      by signals. What kinds of signals do we find moving between these
      components?

    * What is a "multiplexor"?

    * What is a "demultiplexor"?

    * Draw a digram of a basic ALU component showing the signals needed
      to make it work.

    * If a machine needs to send data into one side of 

    * What is a "wait state" and why is it needed?

    * Basically, how is decoding of an instruction accomplished?

..  vim:filetype=rst spell:
